version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=flight-in-portugal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"